### PR TITLE
user auth mvp

### PR DESCRIPTION
**Pull request by ryan-mahoney**
- allows for logging in / logging out
- allows for putting a route under password protection

### CODE REVIEW

**Comment by paulswartz** [comment]
I realize this isn't my application, but is there a reason to re-implement users instead of using `ueberauth_cognito`?

**Comment by ryan-mahoney** [comment]
@paulswartz so this app is very generic in terms of who the user accounts could potentially be for (not limited to MBTA)

**Comment by paulswartz** [comment]
We have non-MBTA folks who log into Cognito as well, if that helps.

**Review by arkadyan — APPROVED** [review]
👍

Review happened via talking

**Comment by ryan-mahoney** [comment]
@paulswartz we're trying to make this app for us, but also an open source app that any organization could run/host themselves, so some architectural choices are affected by that goal

**Comment by paulswartz** [comment]
Even if you're going to store the accounts in the database, I'd still encourage you to look at `ueberauth`. For example, here's the backend which lets you validate the passwords yourself: https://github.com/ueberauth/ueberauth_identity

If you use `ueberauth` now, if we want to integrate this with the rest of our user infrastructure, it'll already be set up rather than requiring a refactoring later on.

**Pull request merged**
